package eu.money.configuration;

import org.sql2o.Connection;
import org.sql2o.Sql2o;

public final class DatabaseSchemaInitializer {

    static void initializeDatabase(Sql2o sql20) {
        try (Connection connection = sql20.beginTransaction()) {

            connection.createQuery("SET DATABASE SQL SYNTAX ORA TRUE").executeUpdate();

            connection.createQuery("create table if not exists account(" +
                    "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "public_id VARCHAR(128)," +
                    "iban VARCHAR(34)," +
                    "owner VARCHAR(200)," +
                    "balance NUMBER(200,0), " +
                    "created_at TIMESTAMP, " +
                    "modified_at TIMESTAMP" +
                    ")"
            ).executeUpdate();

            connection.createQuery(
                    "CREATE INDEX if not exists idx_account_pub_id ON account(public_id)"
            ).executeUpdate();

            connection.createQuery("create table if not exists lock(" +
                    "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "resource_id VARCHAR(128)," +
                    "type VARCHAR(20)," +
                    "UNIQUE (resource_id, type), " +
                    "created_at TIMESTAMP " +
                    ")"
            ).executeUpdate();
        }

    }
}
